language: cpp
dist: bionic

git:
  depth: 1


before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build=missing -s compiler.libcxx=libstdc++11
  - cmake ..
  - cmake --build .
  - ./bin/test_hello

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-bionic-6.0
  - llvm-toolchain-bionic-7.0
  - llvm-toolchain-bionic-8.0

common_packages: &all_packages
  - g++-7
  - g++-8
  - clang-6.0
  - clang-7
  - clang-8
  - libpcre3-dev
  - libpcre2-dev

matrix:
  include:

    # Clang on osx
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++ C_COMPILER=clang"
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++ C_COMPILER=clang"

    # GCC on linux
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: *all_packages
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7 C_COMPILER=gcc-7"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: *all_sources
          packages: *all_packages
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-8 C_COMPILER=gcc-8"

    # Clang on Linux
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages: *all_packages
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++-6.0 C_COMPILER=clang-6.0"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages: *all_packages
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++-7 C_COMPILER=clang-7"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages: *all_packages
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++-8 C_COMPILER=clang-8"

notifications:
  email:
    recipients:
      - utromvecherom@gmail.com
